# Interface festlegen (meist en0 für Ethernet oder USB-Adapter)
interface=en9

# DHCP Range: IPs von .50 bis .150, Lease-Dauer 12 Stunden
dhcp-range=192.168.1.50,192.168.1.150,255.255.255.0,12h

# Gateway (Dein Computer)
dhcp-option=option:router,192.168.1.100

# DNS Server (Google & dein Computer)
dhcp-option=option:dns-server,192.168.1.100,8.8.8.8

# --- ZTP SPEZIFISCH ---
# Option 67: Pfad zum Boot-Skript auf deinem Flask-Server
# guestshell
dhcp-option=67,"http://192.168.1.100/provision/bootstrap.py"
# klassische Config
#dhcp-option=67,"http://192.168.1.100/configs/router_config.conf"

# Logging für Debugging (hilfreich, um zu sehen, ob der Router anfragt)
# laesst sich aber auch gut mit Wireshark ueberpruefen
log-dhcp
